{
	"version": 1716457915,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/foto1-sheet0.png",
		"images/foto1-sheet1.png",
		"images/foto1-sheet2.png",
		"images/foto1-sheet3.png",
		"images/foto1-sheet4.png",
		"images/foto1-sheet5.png",
		"images/foto1-sheet6.png",
		"images/foto1-sheet7.png",
		"images/foto1-sheet8.png",
		"images/foto1-sheet9.png",
		"images/foto1-sheet10.png",
		"images/foto1-sheet11.png",
		"images/foto1-sheet12.png",
		"images/foto1-sheet13.png",
		"images/foto1-sheet14.png",
		"images/foto1-sheet15.png",
		"images/foto1-sheet16.png",
		"images/foto1-sheet17.png",
		"images/foto1-sheet18.png",
		"images/kanan-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/tiledbackground.png",
		"images/foto2-sheet0.png",
		"images/sprite6-sheet0.png",
		"images/sprite7-sheet0.png",
		"images/gedung-sheet0.png",
		"images/gedung-sheet1.png",
		"images/gedung-sheet2.png",
		"images/sprite8-sheet0.png",
		"images/dasar-sheet0.png",
		"images/pov-sheet0.png",
		"images/batas-sheet0.png",
		"images/ruangdosen-sheet0.png",
		"images/kemultimedia-sheet0.png",
		"images/sprite-sheet0.png",
		"images/povlantai1fak-sheet0.png",
		"images/povlantai1fak2-sheet0.png",
		"images/sprite2-sheet0.png",
		"media/mars bsi.ogg",
		"media/mars fah s.ogg",
		"media/himne uin.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}