{
	"version": 1749776605,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/foto1-sheet0.png",
		"images/foto1-sheet1.png",
		"images/foto1-sheet2.png",
		"images/foto1-sheet3.png",
		"images/kanan-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/tiledbackground.png",
		"images/dasar-sheet0.png",
		"images/pov-sheet0.png",
		"images/batas-sheet0.png",
		"images/tiga-sheet0.png",
		"images/sprite-sheet0.png",
		"images/ranahkosong-sheet0.png",
		"images/masuk-sheet0.png",
		"images/masuk-sheet1.png",
		"images/masuk-sheet2.png",
		"images/masuk-sheet3.png",
		"images/masuk-sheet4.png",
		"images/masuk-sheet5.png",
		"images/masuk-sheet6.png",
		"images/about-sheet0.png",
		"images/mainbackground-sheet0.png",
		"images/mainbackground-sheet1.png",
		"images/mainbackground-sheet2.png",
		"images/back-sheet0.png",
		"images/up-sheet0.png",
		"images/tag-sheet0.png",
		"images/sprite9-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/gradient_linear_-sheet0.png",
		"images/gradient_linear_-sheet1.png",
		"images/loc1-sheet0.png",
		"media/the stone roses - bye bye badman.ogg",
		"media/audio.ogg",
		"media/_unseen pressure_.ogg",
		"media/hanging identity.ogg",
		"media/audiomass-output.ogg",
		"media/nur.ogg",
		"media/best slow and relaxing.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}