{
	"version": 1748329445,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/sprite-sheet0.png",
		"images/sprite-sheet1.png",
		"images/sprite-sheet2.png",
		"images/sprite-sheet3.png",
		"images/back-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/joinbutton-sheet0.png",
		"images/periode-sheet0.png",
		"images/particles.png",
		"images/nilai-sheet0.png",
		"images/nilai-sheet1.png",
		"images/confetti-sheet0.png",
		"images/starburst-sheet0.png",
		"media/clappings.ogg",
		"media/song.ogg",
		"media/spongebob disappointed.ogg",
		"media/suction pop.ogg",
		"media/good job.ogg",
		"media/im-sorry-voice.ogg",
		"media/nice try.ogg",
		"media/not bad.ogg",
		"media/fast.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"c2mp-net.js",
		"c2mp-peer.js",
		"c2mp.js",
		"waker.js"
	]
}